EXENAME = sim

MUSASHIFILES = m68kcpu.c m68kdasm.c softfloat/softfloat.c
MAINFILES = sim.c
MUSASHIGENCFILES = m68kops.c
MUSASHIGENHFILES = m68kops.h
MUSASHIGENERATOR = m68kmake

EXE =
EXEPATH = ./

CFILES = $(MAINFILES) $(MUSASHIFILES) $(MUSASHIGENCFILES)
OFILES = $(CFILES:.c=.o)
DFILES = $(CFILES:.c=.d)

CC = gcc
WARNINGS = -Wall -Wextra -pedantic
CFLAGS = $(WARNINGS) -g -O0
LFLAGS = $(WARNINGS)

TARGET = $(EXENAME)$(EXE)
DELETEFILES = $(OFILES) $(TARGET) $(MUSASHIGENERATOR)$(EXE) $(DFILES)

all: $(TARGET)

clean:
	rm -f $(DELETEFILES)

$(TARGET): $(OFILES) Makefile
	$(CC) -o $@ $(OFILES) $(LFLAGS) -lm

$(OFILES): %.o: %.c
	$(CC) $(CFLAGS) -MM -MF $(@:.o=.d) -MT $@ $<
	$(CC) $(CFLAGS) -c $< -o $@

$(MUSASHIGENCFILES) $(MUSASHIGENHFILES): $(MUSASHIGENERATOR)$(EXE)
	$(EXEPATH)$(MUSASHIGENERATOR)$(EXE)

$(MUSASHIGENERATOR)$(EXE): $(MUSASHIGENERATOR).c
	$(CC) -o $(MUSASHIGENERATOR)$(EXE) $(MUSASHIGENERATOR).c

-include $(DFILES)
